# Generated by Django 3.1.1 on 2020-09-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('gb', models.CharField(choices=[(1, '1 GB'), (2, '2 GB'), (4, '4 GB')], default=0, max_length=2)),
                ('used', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
